// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ4BMC6tt8waR9gD_w2NhkvnvqaM5vFu8',
    appId: '1:312655095034:web:8a63ea4ac3867395e45543',
    messagingSenderId: '312655095034',
    projectId: 'finance-873ce',
    authDomain: 'finance-873ce.firebaseapp.com',
    storageBucket: 'finance-873ce.appspot.com',
    measurementId: 'G-2K23EQDVT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgle47FNHC52t0Sy-pYx9LLzKx17FftI',
    appId: '1:312655095034:android:aa3849e27caa6a6fe45543',
    messagingSenderId: '312655095034',
    projectId: 'finance-873ce',
    storageBucket: 'finance-873ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiW7k6frYsig9zCn9hQ1cTmF6rw8Sbiiw',
    appId: '1:312655095034:ios:93d4f390db7212ede45543',
    messagingSenderId: '312655095034',
    projectId: 'finance-873ce',
    storageBucket: 'finance-873ce.appspot.com',
    iosClientId: '312655095034-e6rvupmk7p0evj6q1e5ccgk8avnimdeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiW7k6frYsig9zCn9hQ1cTmF6rw8Sbiiw',
    appId: '1:312655095034:ios:93d4f390db7212ede45543',
    messagingSenderId: '312655095034',
    projectId: 'finance-873ce',
    storageBucket: 'finance-873ce.appspot.com',
    iosClientId: '312655095034-e6rvupmk7p0evj6q1e5ccgk8avnimdeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );
}
